LEAGUES = [
    {
        "key": "br_a",
        "name": "Brazilian Serie A",
        "display_name": "Brasileirão Série A",
        "id": "4351",
        "season": "2025",
        "priority": 1,
    },
    {
        "key": "br_b",
        "name": "Brazilian Serie B",
        "display_name": "Brasileirão Série B",
        "id": "4404",
        "season": "2025",
        "priority": 2,
    },
    {
        "key": "pl",
        "name": "English Premier League",
        "display_name": "Premier League",
        "id": "4328",
        "season": "2025-2026",
        "priority": 1,
    },
    {
        "key": "uel",
        "name": "UEFA Europa League",
        "display_name": "Liga Europa",
        "id": "4481",
        "season": "2025-2026",
        "priority": 1,
    },
    {
        "key": "arg",
        "name": "Argentinian Primera Division",
        "display_name": "Argentina Liga Profesional",
        "id": "4406",
        "season": "2026",
        "priority": 2,
    },
    {
        "key": "ita",
        "name": "Italian Serie A",
        "display_name": "Itália Série A",
        "id": "4332",
        "season": "2025-2026",
        "priority": 1,
    },
    {
        "key": "tur",
        "name": "Turkish Super Lig",
        "display_name": "Turquia Super Lig",
        "id": "4339",
        "season": "2025-2026",
        "priority": 3,
    },
    {
        "key": "ucl",
        "name": "UEFA Champions League",
        "display_name": "Liga dos Campeões",
        "id": "4480",
        "season": "2025-2026",
        "priority": 1,
    },
    {
        "key": "sud",
        "name": "Copa Sudamericana",
        "display_name": "Copa Sul-Americana",
        "id": "4724",
        "season": "2026",
        "priority": 2,
    },
    {
        "key": "lib",
        "name": "Copa Libertadores",
        "display_name": "Libertadores",
        "id": "4501",
        "season": "2026",
        "priority": 1,
    },
    {
        "key": "champ",
        "name": "English League Championship",
        "display_name": "Championship",
        "id": "4329",
        "season": "2025-2026",
        "priority": 2,
    },
    {
        "key": "bundesliga",
        "name": "German Bundesliga",
        "display_name": "Bundesliga",
        "id": "4331",
        "season": "2025-2026",
        "priority": 2,
    },
]